### ISSUE TITLE
Import NCrystal in Jupyter Notebook 

### ISSUE THREAD

**Issue by nicriz** [mctools/ncrystal#116]
Hello!

I am trying to install NCrystal and OpenMC on the ESS cluster at DMSC. The installing script was provided by @marquezj:

```
#!/usr/bin/env bash

# Load modules

module load anaconda/4.8.3
module load gcc/10.2.0
module load cmake/3.18
module load hdf5/1.12.0_gcc1020
module load openmpi/4.0_gcc1020

#
# Install NCrystal and OpenMC in a conda environment in the DMSC cluster
#

# Create installation directory
mkdir -p openmc_ncrystal
cd openmc_ncrystal

conda create -y --name openmc_ncrystal_develop python=3.9
source activate openmc_ncrystal_develop
conda install -y pip

# Install NCrystal
git clone https://github.com/mctools/ncrystal.git
mkdir build_ncrystal
cd build_ncrystal
cmake ../ncrystal -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
make -j 8
make install
source $CONDA_PREFIX/setup.sh
nctool --test
cd ../

# Install OpenMC
git clone --recurse-submodules https://github.com/openmc-dev/openmc.git
cd openmc
git checkout develop
cd ../
mkdir build_openmc
cd build_openmc
cmake ../openmc -DOPENMC_USE_NCRYSTAL=on -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
make -j 8
make install
cd ../openmc
pip install .
cd ../

conda install -y pip jupyter
```
The output is saved in the attached log file
[log_install.txt](https://github.com/mctools/ncrystal/files/10663501/log_install.txt)

importing NCrystal from the Python interpreter (inside the openmc_ncrystal_develop env) works smoothly:
``` 
(openmc_ncrystal_develop) [nicola.rizzi@r2n38 ~]$ python 
Python 3.9.16 (main, Jan 11 2023, 16:05:54) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import NCrystal
>>>
 ```
But when I try to import it in a python notebook on the same kernel:

 ``` 
OSError                                   Traceback (most recent call last)
Cell In[1], line 4
      2 import matplotlib.pyplot as plt
      3 import openmc
----> 4 import NCrystal as NC

File ~/.conda/envs/openmc_ncrystal_develop/share/NCrystal/python/NCrystal/__init__.py:833
    830     _wrap('ncrystal_remove_all_data_sources',None,tuple())
    831     return functions
--> 833 _rawfct = _load(_find_nclib())
    835 def decodecfg_packfact(cfgstr):
    836     """OBSOLETE FUNCTION (always returns 1.0 now)."""

File ~/.conda/envs/openmc_ncrystal_develop/share/NCrystal/python/NCrystal/__init__.py:216, in _load(nclib_filename)
    214 def _load(nclib_filename):
--> 216     _nclib = ctypes.CDLL(nclib_filename)
    217     _int,_intp,_uint,_uintp,_dbl,_dblp,_cstr,_voidp = (ctypes.c_int, ctypes.POINTER(ctypes.c_int),
    218                                                        ctypes.c_uint,ctypes.POINTER(ctypes.c_uint), ctypes.c_double,
    219                                                        ctypes.POINTER(ctypes.c_double), ctypes.c_char_p, ctypes.c_void_p)
    220     _ulong = ctypes.c_ulong

File ~/.conda/envs/openmc_ncrystal_develop/lib/python3.9/ctypes/__init__.py:382, in CDLL.__init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    379 self._FuncPtr = _FuncPtr
    381 if handle is None:
...
--> 382     self._handle = _dlopen(self._name, mode)
    383 else:
    384     self._handle = handle

OSError: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /users/nicola.rizzi/.conda/envs/openmc_ncrystal_develop/lib64/libNCrystal.so)
 ```

Since the error is pointing to GLIBC issue I am really confused on what could cause it. Any idea on possible debugging actions? 

Thanks in advance for the help

**Comment by tkittel** [comment]
Hi @nicriz !

So glibc errors coupled with conda are... not that surprising :-)

I don't believe this is an actual NCrystal bug, but rather a bug in your setup. A few hints that might help you solve the issue:

1. You can install NCrystal via conda ("conda install -c conda-forge ncrystal").
2. You should make sure the whole stack (including compilers and cmake) are provided via conda, and you should most certainly not mix up system provided tools like gcc and cmake with those from conda (btw. I only use the conda-forge channel for everything).
3. Using cmake inside a conda environment can be a bit tricky. I believe at the very least that you have to add the content of `$CMAKE_ARGS` to your cmake (i.e. type `cmake ${CMAKE_ARGS} ... ` instead of `cmake ...`.
4. I am not 100% sure, but I think you also need to add the `compilers` conda-forge meta-package to your dependencies.

I haven't tested, but perhaps this conda environment would be a good starting point?:

```
name: whatever
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python
  - compilers
  - numpy
  - matplotlib
  - cmake
  - git
  - ncrystal
  - mcpl
  - pip
  - make
  - dagmc #optional
```

**Comment by tkittel** [comment]
You can perhaps guess more dependencies by looking in the recipe for openmc:

https://github.com/conda-forge/openmc-feedstock/blob/main/recipe/meta.yaml

(one day I hope we can simply have an ncrystal flag for the openmc conda-forge package).

**Comment by nicriz** [comment]
Hi @tkittel thanks for the reply! After yesterday I also believe it is a problem in my setup. I will post what worked for me for future reference.

Cheers

**Comment by nicriz** [comment]
So the problem was that I was running the jupyter kernel in an environment without the gcc library loaded. Everything was made harder to debug becasue I was not manually starting the kernel, but the VScode extension was taking care of that. So my workaround was to setup the jupyter kernel in the correct environment in a screen session (permanently running on the cluster)  and then access this kernel manually adding it to the VSCode extension. My solution is somewhat similar to [this guide](https://medium.com/@francisferreiracunha/vscode-remote-jupyter-server-setup-12992a11bba8), but taking the shortcut of also running VSCode remotely (so no need of local connection to the forwarded port).

**Comment by tkittel** [comment]
Wow... I might be old fashioned, but I am happy I don't work in your setup ;-)
