### ISSUE TITLE
ncrystal 3.5.1 installation problem on MacOS (M1)

### ISSUE THREAD

**Issue by riwa73** [mctools/ncrystal#118]
When I build and install ncrystal on my Macmini (M1)
I get the following errors running:

`ncrystal_inspectfile --help`
or 
`import NCrystal` 
in my Python environment

`import NCrystal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wagnerrichard/ncrystal/share/NCrystal/python/NCrystal/__init__.py", line 833, in <module>
    _rawfct = _load(_find_nclib())
  File "/Users/wagnerrichard/ncrystal/share/NCrystal/python/NCrystal/__init__.py", line 216, in _load
    _nclib = ctypes.CDLL(nclib_filename)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/wagnerrichard/ncrystal/lib/libNCrystal.dylib, 0x0006): tried: '/Users/wagnerrichard/ncrystal/lib/libNCrystal.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/wagnerrichard/ncrystal/lib/libNCrystal.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/wagnerrichard/ncrystal/lib/libNCrystal.dylib' (no such file), '/Users/wagnerrichard/ncrystal/lib/libNCrystal.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))`

my target system is _arm64_ but it seems to expect _x86_64_ libraries.

Any suggestions?  
Thanks,
Richard

**Comment by riwa73** [comment]
Hi Thomas,
you were right - somehow my Python installation was messed up.
I went to the newest version 3.11 and after some hazzle it now works.
Thanks for your patience!

**Comment by tkittel** [comment]
No problem, "somehow my Python installation was messed up" is how I always find myself on OSX ;-)

Btw., in case it is useful, notice that NCrystal is also available for installation via conda (in the conda-forge channel) now.
