### ISSUE TITLE
Constants in the new release

### ISSUE THREAD

**Issue by marquezj** [mctools/ncrystal#120]
I think this constant here should be changed to `NCrystal.constants.const_neutron_mass_amu`:

https://github.com/mctools/ncrystal/blob/a263fb0efa4550239ef9fe7bb22e63d951d56206/ncrystal_python/ncrystal_endf2ncmat#L274

**Comment by tkittel** [comment]
Absolutely, thanks! Due to the pyne dependency, the endf2ncmat script is not properly unit tested currently. I will make the update.

**Comment by tkittel** [comment]
(and there is actually another similar error in the same file)

**Comment by tkittel** [comment]
So I think a fix for this is in the develop branch now - but would be good if you can verify, since I don't have time to install pyne right now the fix is a bit theoretical.

**Comment by tkittel** [comment]
Yep, seems to work (at least converting one file worked).

**Comment by tkittel** [comment]
Was fixed, closing.
