### ISSUE TITLE
NCrystal material with orientation in Geant4

### ISSUE THREAD

**Issue by MilanKlausz** [mctools/ncrystal#16]
The NCystal material in the [Geant4 example](https://github.com/mctools/ncrystal/blob/master/examples/ncrystal_example_g4sim.cc) is not oriented and it took me some time to figure out how to do it.

I've tried to do something like this:
`addParameterString("material_sample_ncrystal","NCrystal:cfg=C_sg194_pyrolytic_graphite.ncmat;dir1=@crys_hkl:0,0,2@lab:0,0,-1;dir2=@crys_hkl:0,2,0@lab:0,1,0;mos=60arcmin");`
and later:
`getParameterMaterial("material_sample_ncrystal");`
but the _NamedMaterialProvider::MatInfo::MatInfo(const std::string& ss)_ function doesn't like the colons in the definition of the directions and it gives the following error:

> G4Launcher:: NamedMaterial ERROR in material "NCrystal:cfg=C_sg194_pyrolytic_graphite.ncmat;mos=60arcmin;dir1=@crys_hkl:0,0,2@lab:0,0,-1;dir2=@crys_hkl:0,2,0@lab:0,1,0": syntax error in parameter definition

Thanks to a helpful comment in the _MatInfo_ function I was able to solve it by writing square bracket
around the value of the _cgf_ parameter:
`addParameterString("material_sample_ncrystal","NCrystal:cfg=[C_sg194_pyrolytic_graphite.ncmat;dir1=@crys_hkl:0,0,2@lab:0,0,-1;dir2=@crys_hkl:0,2,0@lab:0,1,0;mos=60arcmin]");`

If this solution is indicated somewhere in NCrystal's documentation and I've missed it than I deserved to struggle with it, otherwise it should be indicated somewhere. :)

**Comment by tkittel** [comment]
Hi Milan,

Thanks for the detailed report as usual. So you are right, semicolons in strings is not allowed when using the NamedMaterial interface of the ESS dgcode framework, and this gives errors when attempting to use NCrystal cfg strings with such semicolons inside them. The solution you found is the correct one, enclose the trouble-some string in square brackets in the NamedMaterial strings.

So this is certainly not an NCrystal bug, but I will make sure that the NamedMaterial documentation + error message will point out the []'s so it will hopefully be clear in the future.

Cheers,
Thomas

**Comment by tkittel** [comment]
The NamedMaterial docs does mention this (since some time) it seems, so closing.
