### ISSUE TITLE
return information from hklList in a python structure

### ISSUE THREAD

**Issue by soerenschmidts** [mctools/ncrystal#164]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
easy access to components in hklList from python

**Comment by tkittel** [comment]
Hi @soerenschmidts ,

I guess it makes sense to have a more convenient method that returns data in e.g. numpy arrays (assuming one does not need the list of normals or specific hkl indices of a particular hkl family).

But a question is of course more specifically what you (and other users) would find useful? Do you just want d-spacings, multiplicities and f-squared, or also a representative hkl index. Do you need the ability to request just some (e.g. only those above some d-cutoff or the N entries with the longest d-spacing), or is the `dcutoff` parameter that one can apply in the cfg-string already sufficient for this?

Cheers,
Thomas

**Comment by tkittel** [comment]
Hi @soerenschmidts,

Could you let me know exactly what form you had in mind?

Cheers,
Thomas

**Comment by soerenschmidts** [comment]
Hi Thomas,

Tnx, the new interface will supply the info needed nicely

Soeren

**Comment by tkittel** [comment]
Great, thanks for checking! There was an issue with this functionality in release 3.9.0, but release 3.9.1 is now out so it should work there!
