### ISSUE TITLE
Multithread-friendly NCrystal::scatter

### ISSUE THREAD

**Issue by andrmor** [mctools/ncrystal#18]
Could you make `NCrystal::Scatter` multithread-friendly?

At least for these two methods:
```
crossSectionNonOriented()
generateScatteringNonOriented()
```
They are defined as const, can make someone think they are already safe.

Regards,
Andrey

**Comment by tkittel** [comment]
Thanks for the request, I agree that at the very least the various methods NCrystal::Scatter should be MT safe. It won't be done in the very near future, but it is on the radar! :-)

**Comment by andrmor** [comment]
One more thing: for full multithread support it should be possible to give each NCrystal::scatter a pointer to it's own random generator. For example, TRandom2 from cern root seems to be not thread safe.

**Comment by andrmor** [comment]
Thomas has pointed out that scatter has a method setRandomGenerator().
However, the createScatter() static function return const NCrystal::Scatter *.

I propose to decouple configuration and execution, also making it safer for multithread approach:
Let crossSectionNonOriented() and generateScatteringNonOriented() methods have one extra argument giving the pointer to the random generator. If the pointer is zero, the current implementation is in effect, otherwise the provided generator is used.

**Comment by tkittel** [comment]
First tiny step is now implemented: Internally, the random number streams are now more decoupled from the scatter classes themselves. This won't make any outwards changes, but is a necessary precursor for the future MT developments.

**Comment by tkittel** [comment]
FYI, the plan is to finally look into this before the end of the year.

**Comment by tkittel** [comment]
Hi @andrmor !

So NCrystal v2.5.0 is out now, and it FINALLY has exactly what you requested:

https://github.com/mctools/ncrystal/wiki/Announcement-Release2.5.0

It is even supposed to support MT-safe initialisation as well (i.e. you can initialise different materials in different threads for speedup).

Sorry it took so long, but to solve this properly I basically needed to do a full-blown redesign of most of NCrystal's code.

I realise you might not be working on this right this moment, but let me know (here or privately) of any questions or migration support I can provide, when you get around to try out this latest release.

Cheers,
Thomas
