### ISSUE TITLE
Request for gamma-iron .ncmat file

### ISSUE THREAD

**Issue by kalliopikanaki** [mctools/ncrystal#2]
We would like to be able to use crystalline steel as a material within the DG simulation framework (He3Tubes and perhaps MultiGrid, i.e. the material of the He3 walls and the detector vacuum tank respectively). We have been advised to represent this as γ-iron. I am placing a request for producing the .ncmat file.

**Comment by tkittel** [comment]
Assigning to @xxcai1 is currently on leave until mid March, but should have a look then. @xxcai1 we should also discuss having a public documentation somewhere with instructions for how to reliably create these files (it is of course complicated).

**Comment by tkittel** [comment]
While waiting for @xxcai1 (who is now away for easter), here is a file to get you started:

```
NCMAT v1
####################################################################################
## NCMAT file autogenerated by NCrystal v0.9.9 from input at
##
## https://bitbucket.org/mirkoboin/nxs/src/dcb12b6559c399eb644b385539ae71f320ccd414/libnxs/nxs-files/Fe_gamma.nxs
##
## This file has not been validated by NCrystal developers.
####################################################################################
@CELL
    lengths 3.587 3.587 3.587
    angles 90 90 90
@SPACEGROUP
    225
@ATOMPOSITIONS
    Fe 0 0 0
    Fe 0 0.5 0.5
    Fe 0.5 0 0.5
    Fe 0.5 0.5 0
@DEBYETEMPERATURE
    Fe 464
```

I simply converted it from Fe_gamma.nxs and didn't do any validation whatsoever. So you can use it to get started and later on @xxcai1 will add a proper one to our data library page (assuming EXFOR data exists with which to validate).

**Comment by tkittel** [comment]
@kalliopikanaki is it still the case like you told me privately that you are not needing this material anymore?

**Comment by tkittel** [comment]
So actually this issue is related to issue #19, since you actually would like to model steel. We still need the gamma-iron of course :-)

**Comment by tkittel** [comment]
Closing this issue, we can revisit if it becomes needed.
