### ISSUE TITLE
MatCfg : new parameter (fileName -> string& of its content)

### ISSUE THREAD

**Issue by andrmor** [mctools/ncrystal#20]
If it is not against the philosophy of the library, could you add another way of creating MatCfg:

Instead of the file name, it would be great to be able to provide the reference to the string with the file content (const std::string&). In this way the file can be completely avoided which is convenient in some cases.

Regards,
Andrey

**Comment by tkittel** [comment]
It is certainly not against the philosophy to support in-memory files for specialised applications, and I have been thinking about that in the past. Of course, bear in mind that eventually data files might get rather sizeable when we get around to releasing NCrystal with support for scattering kernels (this will finally get you correct energy transfers for the inelastic parts).

Technically, it will require a bit of code redesign and refactoring though. Also, I imagine that we don't want to demand than any file loading plugin will have to support this, but we will make sure that the one reading `.ncmat` files will.

**Comment by tkittel** [comment]
So FYI I will address this in the near future, in connection with work on Scattering Kernels, and a general revamp of the .ncmat parsing code.

**Comment by xxcai1** [comment]
10-4

**Comment by tkittel** [comment]
So @andrmor this is finally supported in NCrystal v2.1.0. You can even set the cmake flag EMBED_DATA=ON, which will cause the NCrystal library to be built with the entire standard NCrystal data library "baked in" :-)
