### ISSUE TITLE
Windows10/Visual studio installation

### ISSUE THREAD

**Issue by matteobsu** [mctools/ncrystal#38]
Hello everyone,

I’m trying to install the latest Ncrystal build downloaded from github (as of June 18 2020), but I am experiencing issues with the Cmake installation.

After following the installation guide I’m getting the errors you can see in the attached pictures (of cmake and visual studio versions).

**And this log:**

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler:  
Build flags: 
Id flags:  

The output was:
1
Microsoft (R) Build Engine version 16.5.1+4616136f8 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 6/18/2020 2:11:59 PM.
Project "C:\Users\busi_m\Workspace\ncrystal\build2\CMakeFiles\3.16.6\CompilerIdC\CompilerIdC.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(449,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [C:\Users\busi_m\Workspace\ncrystal\build2\CMakeFiles\3.16.6\CompilerIdC\CompilerIdC.vcxproj]
  Creating directory "Debug\CompilerIdC.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdC.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc142.pdb" /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
  CMakeCCompilerId.c
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdC.lib" /MACHINE:X64 Debug\CMakeCCompilerId.obj
LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\Users\busi_m\Workspace\ncrystal\build2\CMakeFiles\3.16.6\CompilerIdC\CompilerIdC.vcxproj]
Done Building Project "C:\Users\busi_m\Workspace\ncrystal\build2\CMakeFiles\3.16.6\CompilerIdC\CompilerIdC.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\Users\busi_m\Workspace\ncrystal\build2\CMakeFiles\3.16.6\CompilerIdC\CompilerIdC.vcxproj" (default target) (1) ->
(PrepareForBuild target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(449,5): warning MSB8003: The WindowsSDKDir property is not defined. Some build tools may not be found. [C:\Users\busi_m\Workspace\ncrystal\build2\CMakeFiles\3.16.6\CompilerIdC\CompilerIdC.vcxproj]

"C:\Users\busi_m\Workspace\ncrystal\build2\CMakeFiles\3.16.6\CompilerIdC\CompilerIdC.vcxproj" (default target) (1) ->
(Link target) -> 
  LINK : fatal error LNK1181: cannot open input file 'kernel32.lib' [C:\Users\busi_m\Workspace\ncrystal\build2\CMakeFiles\3.16.6\CompilerIdC\CompilerIdC.vcxproj]

![cmake_err](https://user-images.githubusercontent.com/15745811/85018434-7888bc00-b16d-11ea-8bbb-7f3c75aff3ea.png)
![visualstudio](https://user-images.githubusercontent.com/15745811/85018437-79215280-b16d-11ea-97e2-73d7d568487f.png)
![visualstudio_v](https://user-images.githubusercontent.com/15745811/85018442-79b9e900-b16d-11ea-9b45-31c32b10f5a1.png)

**Comment by tkittel** [comment]
Thanks for the report @matteobsu . I can't really help much with Windows, as I don't have access to a Windows machine, and I haven't really any experience developing on that platform. In the past @andrmor provided some feedback, suggestions and patches for NCrystal to be able to work on windows. @andrmor, if you have the time, do you perhaps have a suggestion for @matteobsu ?

Having said that, it looks to me like there is something incomplete in your build environment, but how to fix it is beyond me. If you/we can't get any windows experts to help, I suggest you consider if you can find a Linux or OSX machine (perhaps just in a virtual machine), since that is where all developers and main users are currently working (to my knowledge).

Cheers,
Thomas

**Comment by andrmor** [comment]
Hi guys, sorry I cannot help in this matter. I have completely abandoned Windows for a couple of years already and now use only Linux.

**Comment by matteobsu** [comment]
Hi again,

I've got help from Anders Kaestner and we found a solution that made it work on a windows 10 pc with visual studio 2019 installed. Apparently the cmake was not compiling due to a missing package in the installation of Visual studio...  as you can see from the screenshot the SDK version that is printed by Cmake is blank.

So I've reinstalled visual studio including the Desktop development in c++ workload and it worked with no problems.

My recommended six steps guided to get it working on windows are:

1. install visual studio 2019 - make sure to tick the Desktop development in c++ workload
2. install cmake https://cmake.org/download/
3. using the cmake gui set source folder to the ncrystal folder pulled from github
4. open as admin the visual studio "Developer command prompt for VS 2019" (can be found from the windows button and browsing the visual studio items)
5. build using the command :e.g. cmake --build C:\Users\busi_m\Workspace\Tools\ncrystal\new_build --config Release
6. install with the command: e.g. cmake --install C:\Users\busi_m\Workspace\Tools\ncrystal\new_build

this should by default setting install NCrystal in C:\Program Files (x86)\NCrystal

Now NCrystal module can be imported in python using e.g.
import os
import sys
os.environ['NCRYSTAL_LIB'] = 'C:/Program Files (x86)/NCrystal/bin/NCrystal.dll'
sys.path.append('C:/Program Files (x86)/NCrystal/python')
import NCrystal

Cheers,
Matteo

**Comment by tkittel** [comment]
Thanks a lot @matteobsu , not only did you solve the problem for yourself, you also took the time to provide a recipe for other windows users. Much appreciated!

I'll probably include your instructions in the next NCrystal release (which should be out in a few weeks).

**Comment by tkittel** [comment]
Actually, @matteobsu I have a small question regarding the line:
```python
os.environ['NCRYSTAL_LIB'] = 'C:/Program Files (x86)/NCrystal/bin/NCrystal.dll'
```
Did the NCrystal.dll file really end up in NCrystal/bin rather than NCrystal/lib ? I wonder if my cmake file does something wrong on Windows. In any case, I will modify the NCrystal python code to also look for bin/NCrystal.dll, so once the next big release is out (~few weeks from now), you should be able to just do:

```python
import sys
sys.path.append('C:/Program Files (x86)/NCrystal/python')
import NCrystal
```

**Comment by matteobsu** [comment]
Hi @tkittel 

I've just doubled checked. I can confirm by default settings it ends there.

Meanwhile, besides it is out of the topic. I'm starting to test the software with this paper as a reference:
https://www.sciencedirect.com/science/article/pii/S0010465519302280

I reckon that's the most documented way to learn how to handle the software right?

Cheers,
Matteo

**Comment by tkittel** [comment]
Hi @matteobsu ,

Yes, that paper is so far the best piece of documentation we have. Of course, it does not go into details about the actual elastic or inelastic physics models, but hopefully one day we will have more publications concerning those as well :-)

Cheers,
Thomas

**Comment by tkittel** [comment]
Release 2.0.0 is out, and I added a (very) small note about windows in the INSTALL file, so closing here - thanks!

Btw., in addition to the paper you mentioned @matteobsu , you can now find an overview of changes for inelastic scattering in the new release at: https://github.com/mctools/ncrystal/wiki/Announcement-Release2.0.0
