### ISSUE TITLE
cfg object needs way to exclude particular factory

### ISSUE THREAD

**Issue by tkittel** [mctools/ncrystal#51]
Use case: From the factory of a SANS plugin, it should be possible to call `globalCreateScatter` to create the non-SANS modles, and thus avoid delegation back to the SANS factory itself.

A workaround is to select the stdscat factory directly via: `cfg2=cfg.clone(); cfg2.set_scatfactory("stdscat")` but it means the SANS plugin won't work with another plugin. Better would be `cfg2.exclude_scatfactory("TheSANSFactoryName")`, somehow.

**Comment by tkittel** [comment]
In the new release, v2.3.0, the globalCreateScatter function used from within a factory will automatically exclude the factory itself from consideration (by default). Thus, the `set_scatfactory("stdscat")` workaround is no longer needed. In fact, it should be removed, to enable multiple plugins working together.

**Comment by tkittel** [comment]
@nicriz, you can/should remove the following lines in your plugin:
```C++
  auto cfg2 = cfg.clone();
  cfg2.set_scatfactory("stdscat"); //select the standard one
  auto sc_std = globalCreateScatter(cfg2);
```
with just:
```C++
  auto sc_std = globalCreateScatter(cfg);
```

**Comment by nicriz** [comment]
Thank you @tkittel. I will do it indeed!
