### ISSUE TITLE
Geant4 compilation error

### ISSUE THREAD

**Issue by rahulm41** [mctools/ncrystal#64]
I am facing errors 'undefined references to '. All functions in the source files are perfectly defined. please help me out in solving the issue?

CMakeFiles/cyliSD.dir/src/ExN01PhysicsList.cc.o: In function `ExN01PhysicsList::ConstructEM()':
ExN01PhysicsList.cc:(.text+0x32a): undefined reference to `G4LowEnergyCompton::G4LowEnergyCompton(G4String const&)'
ExN01PhysicsList.cc:(.text+0x379): undefined reference to `G4LowEnergyPhotoElectric::G4LowEnergyPhotoElectric(G4String const&)'
ExN01PhysicsList.cc:(.text+0x3ae): undefined reference to `G4LowEnergyPhotoElectric::ActivateAuger(bool)'
ExN01PhysicsList.cc:(.text+0x3da): undefined reference to `G4LowEnergyPhotoElectric::SetCutForLowEnSecPhotons(double)'
ExN01PhysicsList.cc:(.text+0x406): undefined reference to `G4LowEnergyPhotoElectric::SetCutForLowEnSecElectrons(double)'
ExN01PhysicsList.cc:(.text+0x457): undefined reference to `G4LowEnergyRayleigh::G4LowEnergyRayleigh(G4String const&)'
ExN01PhysicsList.cc:(.text+0x520): undefined reference to `G4LowEnergyIonisation::G4LowEnergyIonisation(G4String const&)'
ExN01PhysicsList.cc:(.text+0x54f): undefined reference to `G4LowEnergyIonisation::ActivateAuger(bool)'
ExN01PhysicsList.cc:(.text+0x578): undefined reference to `G4LowEnergyIonisation::SetCutForLowEnSecPhotons(double)'
ExN01PhysicsList.cc:(.text+0x5a1): undefined reference to `G4LowEnergyIonisation::SetCutForLowEnSecElectrons(double)'
ExN01PhysicsList.cc:(.text+0x5f7): undefined reference to `G4LowEnergyBremsstrahlung::G4LowEnergyBremsstrahlung(G4String const&)'
ExN01PhysicsList.cc:(.text+0x920): undefined reference to `G4hLowEnergyIonisation::G4hLowEnergyIonisation(G4String const&)'
ExN01PhysicsList.cc:(.text+0xa64): undefined reference to `G4hLowEnergyIonisation::G4hLowEnergyIonisation(G4String const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/cyliSD.dir/build.make:370: recipe for target 'cyliSD' failed
make[2]: *** [cyliSD] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/cyliSD.dir/all' failed
make[1]: *** [CMakeFiles/cyliSD.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Thanks in advance

**Comment by tkittel** [comment]
Sorry, but that doesn't seem to have anything to do with NCrystal. At best it looks like a report for Geant4, but in any case you need to provide a lot more info about what you are doing before anyone will be able to help you there.

**Comment by rahulm41** [comment]
> Sorry, but that doesn't seem to have anything to do with NCrystal. At best it looks like a report for Geant4, but in any case you need to provide a lot more info about what you are doing before anyone will be able to help you there.

first of all thanks for responding. I am doing a project in which I am calibrating the efficiencies of scintillation detector. I have used Standard package now I want to do the same work using lowEnergyEm package when i am applying this package i am getting the same error like-
ExN01PhysicsList.cc:(.text+0x54f): undefined reference to `G4LowEnergyIonisation::ActivateAuger(bool)'
ExN01PhysicsList.cc:(.text+0x578): undefined reference to `G4LowEnergyIonisation::SetCutForLowEnSecPhotons(double)'

**Comment by tkittel** [comment]
As I wrote, this is an issue for the Geant4 project, not NCrystal.

**Comment by rahulm41** [comment]
Now i am confused, have I posted this isue on right platfarm?

**Comment by tkittel** [comment]
Not sure what you mean by that, but for the third time: you have NOT posted your issue in the right place. This is an issue tracker for NCrystal, you are having issues with non-NCrystal Geant4.

**Comment by rahulm41** [comment]
Thanks Kittel, Now I know from where I can get solution of my problems in Github.
