### ISSUE TITLE
Import sys missing in ncrystal_hfg2ncmat

### ISSUE THREAD

**Issue by marquezj** [mctools/ncrystal#71]
https://github.com/mctools/ncrystal/blob/029831471e62c45c7a00633fb541568081b4cec4/ncrystal_python/ncrystal_hfg2ncmat#L34

As the title say, if NCrystal is not found, sys is needed in line [40](https://github.com/mctools/ncrystal/blob/029831471e62c45c7a00633fb541568081b4cec4/ncrystal_python/ncrystal_hfg2ncmat#L40) to add to the path, but it is not imported.

**Comment by tkittel** [comment]
Yes, this was fixed in release 2.7.3.
