### ISSUE TITLE
Spaces in PATH break bootstrap.sh ncplugin-template

### ISSUE THREAD

**Issue by nicriz** [mctools/ncrystal#73]
Similarly to issue #52, spaces in PATH typical of a WSL environment break the ncplugin-template/testcode/utils/bootstrap.sh script for plugin testing

The line is 105:

        export $1=${P:1:99999}

The solution 

         export $1="${P:1:99999}" 

works for me.
Cheers

**Comment by tkittel** [comment]
Applied in dgcode and ncrystaldev repos as well, closing.
