### ISSUE TITLE
ncrystal_inspectfile return core dumped

### ISSUE THREAD

**Issue by nicriz** [mctools/ncrystal#74]
Hallo, I am having the following strange behavior in the  [SANSND plugin](https://github.com/highness-eu/ncplugin-SANSND/tree/testing_v2.0):

When I use the macro testcode/scripts/plotviancrystal where NC.registerInMemoryFileData() and NC.createScatter() are called I have no problem in visualizing cross sections and in general everything looks fine. Also compiling with ncpluginbuild gives no error.

However, if I call

    ncrystal_inspectfile ncplugin-SANSND_nanodiamond.ncmat

after having statically compiled the plugin I get:

     Segmentation fault (core dumped)

or:

      Traceback (most recent call last):
      File "/home/nicorizzi/ncrystal_install/bin/ncrystal_inspectfile", line 589, in <module>
      main()
      File "/home/nicorizzi/ncrystal_install/bin/ncrystal_inspectfile", line 568, in main
      plot_xsect( cfgs, comp  = args.comp, absorption = args.absorption, pdf=args.pdf )
      File "/home/nicorizzi/ncrystal_install/bin/ncrystal_inspectfile", line 359, in plot_xsect
      xsects = part.crossSectionNonOriented(ekins)
      File "/home/nicorizzi/ncrystal_install/share/NCrystal/python/NCrystal/__init__.py", line 1557, in crossSectionIsotropic
      return _rawfct['ncrystal_crosssection_nonoriented'](self._rawobj,ekin,repeat)
      File "/home/nicorizzi/ncrystal_install/share/NCrystal/python/NCrystal/__init__.py", line 477, in ncrystal_crosssection_nonoriented
      _raw_xs_no_many(scat,ekin_ct,n_ekin,repeat,xs_ct)
      File "/home/nicorizzi/ncrystal_install/share/NCrystal/python/NCrystal/__init__.py", line 257, in fcte
      _raise_err()
      File "/home/nicorizzi/ncrystal_install/share/NCrystal/python/NCrystal/__init__.py", line 235, in _raise_err
      raise e
      NCrystal.NCBadInput: Attempt to use IofQHelper in xs2 sampling when not defined in the SANSND plugin`

Same If I try to run the plugin from a McStas simulation. Ncrystal is updated to the last version and I run the code from a WSL environment. 

To reproduce the error one needs to download the plugin, install it and try to run the command inspectfile.

**Comment by tkittel** [comment]
Hi @nicriz,

For the version that you say seems to work find, i.e. the plotviancrystal script, do you only do plotting of cross sections, or do you actually do any sampling of scattering events? I am asking since it seems the crash occurs only when sampling and you only mention that cross section plotting works fine with plotviancrystal.

Because if your sampling is *always* messed up, then it indicates any old kind of bug in the sampling code. However, if you indeed see different behaviour in different environments, then it is more likely to involve something like a memory corruption issue.

Cheers,
Thomas

**Comment by tkittel** [comment]
Looking at your PhysicsModel.cc model I notice a few suspect things. First of all, please protect any division you are doing against zero division! It is better to be defensive, so you won't waste time later on tracking down these bugs. Both neutron ekin, wavelength, and wavenumber k might be 0. Never divide with these things before checking (and if any 0 you can probably just return the appropriate cross section value for that limit).

Second of all, your many if statements are complicating stuff - it is a nightmare to figure out which variables are set in what mode and to make sure you only use the right stuff in the right case. For instance this:

{code}
if (m_model == "simple")
  {
    if (m_p.has_value())
      SANS_xs = m_p.value() * 25.3e-3 / neutron_ekin;
  }
{code}
What happens if m_model=="simple" but m_p has no value? Then your function will return an undefined value is what will happen (it might be 0 in many cases, but suddenly on some other machine it won't be. At the very least add a check there:
{code}
    if (m_p.has_value())
      SANS_xs = m_p.value() * 25.3e-3 / neutron_ekin;
    else
      NCRYSTAL_THROW(LogicError,"Bad internal state in SANSND plugin");
{code}
That will be better, but not really how I would recommend doing it (hint: a bunch of if-statements and a plethora of coupled and uncoupled variables are very hard to get right - and to keep right). I assume for that we should sit down at some point and cleanup the code together.

I also see from the code that your error message `NCrystal.NCBadInput: Attempt to use IofQHelper in xs2 sampling when not defined in the SANSND plugin` is kind of misleading. From the tests above you can only conclude that m_model is neither "simple" nor "HS-FBA", nor does m_helper have a value. But what if m_model is "GP" or "PPF", which you allow when parsing. Messy!

For the short term I suggest you change your m_model variable to be an enum of the available mode, and that you replace your if statements with switch(m_model) statements. In that case the compiler will help you if you forget to treat some case in some function, and you won't be able to mistype any of these strings.

Adding in a bunch of asserts or checks in the various sections can also in the short term help you track down your issue - i.e. use "defensive programming". Each little code snippet should be written under the assumption that someone might have (originally or later) made some logic mismatch elsewhere, so if you have some specific requirements (k!=0, m_helper has value, etc.) you should verify these requirements at the point of usage.

Cheers,
Thomas

**Comment by nicriz** [comment]
Hi Thomas, thank you so much for your tips and your help. I reshaped the code to include your suggestion (enum, switch and tons of assert). Now the model is given as an int in input (we can make it prettier later). After doing this I checked that all the scripts in testcode work (simpletest, plotxs, plotscat and plotviancrystal). So no old kind of error in sampling Q or CrossSection. Unfortunately the plugin still doesn´t work with inspectfile and hook from McStas. I added some printing just to see what was going on, and it seems again stuck at the calcCrossSection.  In particular it looks like the constructor is called but IofQHelper not initialized.

Error from McStas instrument for Guinier Porod (model 2):
         
        NCrystal::NCMATFactory WARNING: Loading NCMAT data which has @CUSTOM_ section(s). This is OK if intended.
        call to constructor for 1 and 2
        call to calcCrossSection
        m_model: 2
        k: 0.534963
        NCrystal ERROR [LogicError]: Attempt to use not-initialized IofQHelper in xs sampling in the SANSND plugin
        NCrystal terminating due to ERROR

inspectfile sometimes gives Segmentation fault: core dumped, sometimes (yes running multiple times `ncrystal_inspectfile ncplugin-SANSND_nanodiamond.ncmat` gives different errors):

       NCrystal::NCMATFactory WARNING: Loading NCMAT data which has @CUSTOM_ section(s). This is OK if intended.
      call to constructor for 1 and 2
      call to constructor for 1 and 2
      call to constructor for 1 and 2
      call to calcCrossSection
      m_model: 2
      k: 6283.19
      Traceback (most recent call last):
        File "/home/nicorizzi/ncrystal_install/bin/ncrystal_inspectfile", line 589, in <module>
          main()
        File "/home/nicorizzi/ncrystal_install/bin/ncrystal_inspectfile", line 568, in main
          plot_xsect( cfgs, comp  = args.comp, absorption = args.absorption, pdf=args.pdf )
        File "/home/nicorizzi/ncrystal_install/bin/ncrystal_inspectfile", line 359, in plot_xsect
          xsects = part.crossSectionNonOriented(ekins)
        File "/home/nicorizzi/ncrystal_install/share/NCrystal/python/NCrystal/__init__.py", line 1557, in crossSectionIsotropic
          return _rawfct['ncrystal_crosssection_nonoriented'](self._rawobj,ekin,repeat)
        File "/home/nicorizzi/ncrystal_install/share/NCrystal/python/NCrystal/__init__.py", line 477, in ncrystal_crosssection_nonoriented
          _raw_xs_no_many(scat,ekin_ct,n_ekin,repeat,xs_ct)
        File "/home/nicorizzi/ncrystal_install/share/NCrystal/python/NCrystal/__init__.py", line 257, in fcte
          _raise_err()
        File "/home/nicorizzi/ncrystal_install/share/NCrystal/python/NCrystal/__init__.py", line 235, in _raise_err
          raise e
      NCrystal.NCLogicError: Attempt to use not-initialized IofQHelper in xs sampling in the SANSND plugin

I am sorry but for me it doesn´t make any sense that the scripts work but not the rest. I hope you can help me figuring this out,
As a side note: I also tried removing all the optional member and still nothing.

**Comment by tkittel** [comment]
Sounds like an uninitialised memory issue to me, or possibly another kind of memory related error. Are you sure you initialise all your variables? Can you install valgrind and try to use it to debug further?

**Comment by tkittel** [comment]
Trying to browse the code on my phone, so a but difficult. But the line looks suspicious:

std::advance(it_q1,1)

I think it means that the element at it_q1 does not get assigned a proper value. I don't think that it explains your issue though.


--

**Comment by nicriz** [comment]
> I think it means that the element at it_q1 does not get assigned a proper value. I don't think that it explains your issue though

IofQ is initialized as a copy of q and then overwritten component by component. So even if it would skip the it_q1, which I think I correctly defined in std::for_each(IofQ.begin(),it_q1,...), it would still have a value.

I downloaded valgrind , but having issues with making it work in WSL (I know I deserve this punishment for not being a pure linux user)

**Comment by nicriz** [comment]
If I run memcheck on simpletest

     valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --log-file=valgrind-out.txt ncplugin_simpletest 

I get

    ==12795== Memcheck, a memory error detector
    ==12795== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
    ==12795== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
    ==12795== Command: ncplugin_simpletest
    ==12795== Parent PID: 249
    ==12795== 
    ==12795== error calling PR_SET_PTRACER, vgdb might block  <--- Apparently this is related to WSL but not crucial
    ==12795== 
    ==12795== HEAP SUMMARY:
    ==12795==     in use at exit: 0 bytes in 0 blocks
    ==12795==   total heap usage: 150 allocs, 150 frees, 5,710,617 bytes allocated
    ==12795== 
    ==12795== All heap blocks were freed -- no leaks are possible
    ==12795== 
    ==12795== For lists of detected and suppressed errors, rerun with: -s
    ==12795== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

but with inspectfile 

    valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --log-file=valgrind-out.txt ncrystal_inspectfile ncplugin-SANSND_nanodiamond.ncmat

    ==12873== Memcheck, a memory error detector
    ==12873== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
    ==12873== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
    ==12873== Command: /home/nicorizzi/ncrystal_install/bin/ncrystal_inspectfile ncplugin-SANSND_nanodiamond.ncmat
    ==12873== Parent PID: 249
    ==12873== 
    ==12873== error calling PR_SET_PTRACER, vgdb might block

I am guessing I am doing it wrong with inspectfile. Am I using valgrind correctly?

**Comment by tkittel** [comment]
Hmm... First of all you want the memcheck tool, not the leakcheck tool. I normally use these flags:
```
valgrind --tool=memcheck --track-origins=yes --malloc-fill=0x80 --free-fill=0x7f --trace-children=yes
```
And for std::advance: Yes, IofQ gets a value (which is why I wrote that I don't think it explains your issue), but it looked like it was not the value you wanted.

**Comment by tkittel** [comment]
Hmmm... I spent some time now trying, but I have a hard time reproducing the issue here. Also, the way you "added enums" to your code was... interesting. All the trouble and none of the gains :-)

**Comment by nicriz** [comment]
> Hmm... First of all you want the memcheck tool, not the leakcheck tool. I normally use these flags:
> 
> ```
> valgrind --tool=memcheck --track-origins=yes --malloc-fill=0x80 --free-fill=0x7f --trace-children=yes
> ```
> 
I am trying to run it with inspectfile but I think is giving tons of output from different calls. I am a bit lost but trying to wrap my head around it.

> And for std::advance: Yes, IofQ gets a value (which is why I wrote that I don't think it explains your issue), but it looked like it was not the value you wanted.

I checked and you are absolutely right. I removed the std::advance lines.

> Hmmm... I spent some time now trying, but I have a hard time reproducing the issue here. Also, the way you "added enums" to your code was... interesting. All the trouble and none of the gains :-)

You mean you can correctly see the output from ncrystal_inspectfile? And I know I messed up with enum but I was having really hard time yesterday understanding how it works. I wanted to create a type for model that could be initialized only to specific values but I failed. I didn't even manage to define one enum as a public member accessible to all the methods. So yeah... quite on the desperate side here.

**Comment by tkittel** [comment]
Yes, I see some plots from inspectfile which clearly includes some SANS. When I run under valgrind I do indeed see some weird reports, but whenever I investigate they appear to be red herrings. This can maybe be explained by some other memory corruption going on (but one which happens to occur in a manner undetectable to valgrind), but to be honest I am a bit baffled here.

For enums, you simply place them in the class declaration, e.g.:
```
class PhysicsModel final : public NC::MoveOnly {
public:
  enum class model_def : unsigned { FILE=0, PPF=1, GPF=2, HSFBA=3 };
   ...
  PhysicsModel( model_def model, double p0, double p1, double p2, double p3, double p4 );
  ...
```
I used the strongly typed ("enum class") version, which you should generally prefer. I also explicitly specified the underlying integer type and the associated integer values. You should not need them for anything in C++ code, but they might come in handy if you one day want to expose the model_def flag to python code (although it might anyway be better just to do that using strings).

**Comment by nicriz** [comment]
It is painful to admit but, deleting and reinstalling ncrystal solved the problem. 

I have only last question about enum (very weird object): when I need to read from the file (e.g. the string "PPF") the I need to go back to the if clause in createFromInfo():
  
    if (model == "PPF"){ 
    ...
    return PhysicsModel(PPF, p0,p1,p2,p3,p4);
    }

 then from that point on I can simply pass it to the private method def_model m_model and switch on that
correct?

**Comment by tkittel** [comment]
Hmm... that is a bit of an unsatisfying resolution, but let us hope the problem does not resurface.
And for enum's: They are really just dressed-up integers, with only a few specific values allowed. And yes, at the point where you load text data or get called from python or whatever, you have to decode the data into the right enums. But of course, in all other places you should only have the enums.
