### ISSUE TITLE
The unit of the coherent scattering length in The @ATOMDB section 

### ISSUE THREAD

**Issue by GitHubhanxf** [mctools/ncrystal#77]
**Describe the bug**
The unit of the coherent scattering length in The @ATOMDB section is defined as fm, but that in example of Si and Si29 are in 0.1fm according to the data in NIST   https://ncnr.nist.gov/resources/n-lengths/elements/si.html.  Which one is right?

**Comment by tkittel** [comment]
Thanks for reporting this issue @GitHubhanxf, there is certainly something not quite right. But as far as I can tell, the only bug we have is in the examples on https://github.com/mctools/ncrystal/wiki/NCMAT-format (and in the file https://github.com/mctools/ncrystal/blob/master/docs/ncmat_doc.md in the release itself, which is essentially the same file). I checked that both the NIST page and NCrystal wants Si to have a coh_sl of around 4fm, corresponding to around 2 barn of sigma_coherent. And if overriding Si data in an @ATOMDB section (or via the atomdb cfg keyword) then one should indeed write something like "4fm" and not "0.4fm" as the examples mistakenly show.

So I will update the documentation, as I can certainly see how this is rather misleading.

Or did I misunderstand you and you think we have more bugs than just on the doc pages above?

**Comment by GitHubhanxf** [comment]
Thank you for your rapid reply! You are right. It is not be a bug in NCrystal. Sorry for my mistake!
I have checked the problem using VDOS and freegas model and found the fm was right, because the cross section in the low wavelength part in the two models were the same in fm, but there was big difference in 0.1fm.

**Comment by tkittel** [comment]
Yes @GitHubhanxf , I am pretty sure that there is no actual NCrystal bug here, but the documentation was misleading. I have updated the [wiki example](https://github.com/mctools/ncrystal/wiki/NCMAT-format) already, and the documentation shipped with the release will be updated with the next release of NCrystal. Thanks a lot for drawing my attention to this.

Concerning:

> By the way, I advise you to create a file to write the cross section information. Otherwise, I have to read the line in the picture to compare different results.

You can simply extract the cross sections easily using the Python API. For instance, using an interactive python session you can query both the fundamental parameters of a given element or isotope, or you can load a material and extract the final scattering cross sections at a given energy or wavelength:
```python
>>> import NCrystal as NC
>>> atom = NC.atomDB('Si29')
>>> help(atom) #<--- shows you all the methods, what units they use, etc.
print(atom.
>>> a.coherentXS()
2.7759112687119405
>>> a.coherentScatLenFM()
4.699999999999999
>>> a.coherentScatLen()
0.47
>>> sc = NC.createScatter('Si_sg227.ncmat')
>>> sc.xsect(wl=0.01)
2.0196312654518636
>>> sc.xsect(ekin=10)
2.0194814949923665
```
Finally you can also access the entire database of atoms with:
```python
>>> for a in NC.iterateAtomDB():
...     print(a.Z(),a.A(),a.coherentXS())
```

**Comment by GitHubhanxf** [comment]
I get a new way to know the input information now. Thank you.  There is a small mistake:
>>> import NCrystal as NC
>>> a = NC.atomDB('Si29')  #It should be a rather than atom and a.coherentXS() will be workable.

But you have misunderstood me. I want to know the data of cross sections that show in pictures when runing NCrystal, i.e. the cross-sections of coherent elastic, incoherent elastic, inelastic and total.

**Comment by tkittel** [comment]
> I get a new way to know the input information now. Thank you. There is a small mistake:
> 
> > > > import NCrystal as NC
> > > > a = NC.atomDB('Si29')  #It should be a rather than atom and a.coherentXS() will be workable.

yes, that's a typo when I was pasting the code.

> 
> But you have misunderstood me. I want to know the data of cross sections that show in pictures when runing NCrystal, i.e. the cross-sections of coherent elastic, incoherent elastic, inelastic and total.

But that is what I showed you in the second half of the example above. `NC.createScatter(..)` returns a scatter object which returns cross sections. By default it is of course the total, but you can enable or disable components by using the cfg string syntax. I.e. if you use `NC.createScatter('Si_sg227.ncmat;inelas=0')` then you will get only elastic components, etc.

**Comment by tkittel** [comment]
Here are some more flags:
```python
NC.createScatter('...;inelas=0;elas=0;coh_elas=1') # only Bragg diffraction
NC.createScatter('...;inelas=0;elas=0;incoh_elas=1') # only incoherent elastic
NC.createScatter('...;elas=0') # only inelastic
```
We are planning to create a "cookbook" wiki at some point, where we could include such instructions :-)

**Comment by tkittel** [comment]
@GitHubhanxf is it clear to you now how to use the scatter objects, or do you need more examples?

**Comment by GitHubhanxf** [comment]
I have written a small python script which should be put in /ncrystal-install-gcc9.3-geant4.10.7/share/NCrystal/python:

import NCrystal as NC
import csv

atom = NC.atomDB('Si29')
mylog=open('cross-section.csv',mode='w',encoding='utf-8')

sc1=NC.createScatter('Si_sg227.ncmat;inelas=0;elas=0;coh_elas=1')
sc2=NC.createScatter('Si_sg227.ncmat;inelas=0;elas=0;incoh_elas=1')
sc3=NC.createScatter('Si_sg227.ncmat;elas=0')
sc4=NC.createScatter('Si_sg227.ncmat')
print('wavelength','coherent-elastic','incoherent-elastic','inelastic','total',file=mylog)

#to get 1001 points between (0A,20A) and the bin is 0.02
for i in range(1001):
	print(i/50,sc1.xsect(wl=i/50),sc2.xsect(wl=i/50),sc3.xsect(wl=i/50),sc4.xsect(wl=i/50),file=mylog)
mylog.close()

Then I can read get the cross section data in file cross-section.csv.

**Comment by tkittel** [comment]
I am glad you found a solution @GitHubhanxf , but for the sake of anyone else stumbling across this I would like to make a few comments/warnings. First of all, you should in generally not have to place your own python scripts or modules inside the NCrystal installation directories. Assuming you have PYTHONPATH etc. setup correctly, your script should work from anywhere.

Second of all, be aware of the reduced precision you get when you print the values with a default print statement like this (also, 1000 pts is a bit low when dealing with sharp Bragg edges).

Might I suggest another alternative, which also takes advantage of NCrystal's ability to transform Numpy arrays directly:

```python
import NCrystal as NC
import numpy as np

infile='Si_sg227.ncmat'
wls = np.linspace(0.0,20.0,1001)#NB: consider more points
cols = [ ('coh_elas','inelas=0;elas=0;coh_elas=1'),
         ('incoh_elas','inelas=0;elas=0;incoh_elas=1'),
         ('inelas','elas=0'),
         ('total','') ]

xsvals = [ NC.createScatter(f'{infile};{cfg}').xsect(wl=wls) for _,cfg in cols ]
titles = [ title for title,_ in cols ]

#Write csv file with pandas:
import pandas
data = np.vstack([wls]+[xsvals]).T
pandas.DataFrame(data).to_csv("cross-section.csv",
                              header = ['wavelength']+titles,
                              index=False)

#And/or simply plot:
import matplotlib.pyplot as plt
for lbl,xs in zip(titles,xsvals):
    plt.plot(wls,xs,label=lbl)
plt.show()
```

I produce the output with `pandas` since it is convenient and robust, and `to_csv` could be easily changed to e.g. `to_excel`, `to_html`, etc. If you want to avoid it, you can use numpy.savetxt instead (just google it).

Cheers,
Thomas

**Comment by GitHubhanxf** [comment]
Thank you. It is workable.

**Comment by tkittel** [comment]
I don't have any UZr_sg221.ncmat file, but there is certainly a huge difference between temp=1200K and 20K. But just to double-check, are you sure you know how to you type commands in a terminal? If you write:
```sh
ncrystal_inspectfile UZr_sg221.ncmat;temp=1200K
```
It is actually interpreted as two commands, which is not what you want:
```sh
ncrystal_inspectfile UZr_sg221.ncmat
temp=1200K
```
The second one is just setting an environment variable (which won't do much - and won't give an error), and the first one is inspecting the material _without_ your temperature setting. The correct way is to enclose the cfg string in quotes:
```sh
ncrystal_inspectfile "UZr_sg221.ncmat;temp=1200K"
```
Use the --dump option to verify the temperature setting:
```sh
ncrystal_inspectfile --dump "UZr_sg221.ncmat;temp=1200K"
```
And you can directly compare the two temperature values by doing:
```sh
ncrystal_inspectfile "UZr_sg221.ncmat;temp=1200K"  "UZr_sg221.ncmat;temp=20K"
```

I am closing this issue, as it seems we are getting off topic.

Cheers,
Thomas

**Comment by GitHubhanxf** [comment]
> 

Thank you. I have got it. You can close it now.
