### ISSUE TITLE
Request for data extraction

### ISSUE THREAD

**Issue by GitHubhanxf** [mctools/ncrystal#78]
Hello. Would you mind tell me how to get the data of scattering angle？You can add it at your code below.  Or could  you tell me the way to change the form of output picture? Thank you！

import NCrystal as NC
import numpy as np

infile='Si_sg227.ncmat'
wls = np.linspace(0.0,20.0,1001)#NB: consider more points
cols = [ ('coh_elas','inelas=0;elas=0;coh_elas=1'),
         ('incoh_elas','inelas=0;elas=0;incoh_elas=1'),
         ('inelas','elas=0'),
         ('total','') ]

xsvals = [ NC.createScatter(f'{infile};{cfg}').xsect(wl=wls) for _,cfg in cols ]
titles = [ title for title,_ in cols ]

#Write csv file with pandas:
import pandas
data = np.vstack([wls]+[xsvals]).T
pandas.DataFrame(data).to_csv("cross-section.csv",
                              header = ['wavelength']+titles,
                              index=False)

#And/or simply plot:
import matplotlib.pyplot as plt
for lbl,xs in zip(titles,xsvals):
    plt.plot(wls,xs,label=lbl)
plt.show()

**Comment by tkittel** [comment]
Hi @GitHubhanxf 

It depends on what you mean with "data of scattering angle". Depending on your material and your version of NCrystal, you can use the sampleIsotropic(..) scatter method to sample a single scattering. To get a distribution you will have to sample it many times. Note that the method might be named differently depending on your version of NCrystal, you can for instance use "help(NC)" or "help(NC.Scatter)" in Python to learn more.

Also, if you didn't already, please read https://www.sciencedirect.com/science/article/pii/S0010465519302280 as it might help you understand a bit better how NCrystal works. It might also be worthwhile for you to improve your Python skills a bit, so you understand how to access the builtin documentation of the NCrystal Python module.

Cheers,
Thomas
